markdown: kramdown
permalink: /:title/
url: http://www.hkjdy.cn
name: 格修
author: 格修
qq: 416266282
email: hkjdy@163.com
beian: 京ICP备14054711号
weibo: hkjdy
github: hkjdy
pygments: true
safe: true
paginate: 20
about: "这里是格修的博客"
baseurl: ''