markdown: rdiscount
permalink: /:title/
url: http://www.hkjdy.cn
name: 格修
author: 格修
qq: 416266282
email: hkjdy@163.com
duoshuo: yonsm
beian: 京ICP备14054711号
cnzz: 119959
weibo: 1885061391
github: hkjdy
pygments: true
safe: true
paginate: 20
about: "这里是格修的博客"
baseurl: ''